// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKpiRAR_Izbgae4YnPqT-3CSzDRyu4pw8',
    appId: '1:164188610636:web:c3218e045d5965a4ac14e9',
    messagingSenderId: '164188610636',
    projectId: 'hu-app-b200b',
    authDomain: 'hu-app-b200b.firebaseapp.com',
    storageBucket: 'hu-app-b200b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWt8-rQdcHLkjfinXfyF-VxgrsFUJ3Tw',
    appId: '1:164188610636:android:c3218e045d5965a4ac14e9',
    messagingSenderId: '164188610636',
    projectId: 'hu-app-b200b',
    storageBucket: 'hu-app-b200b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKpiRAR_Izbgae4YnPqT-3CSzDRyu4pw8',
    appId: '1:164188610636:ios:27667d45555f4e1eac14e9',
    messagingSenderId: '164188610636',
    projectId: 'hu-app-b200b',
    storageBucket: 'hu-app-b200b.firebasestorage.app',
    iosBundleId: 'com.hu.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKpiRAR_Izbgae4YnPqT-3CSzDRyu4pw8',
    appId: '1:164188610636:ios:27667d45555f4e1eac14e9',
    messagingSenderId: '164188610636',
    projectId: 'hu-app-b200b',
    storageBucket: 'hu-app-b200b.firebasestorage.app',
    iosBundleId: 'com.hu.app',
  );
}
