// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1nd5Li1onmSYGE9TqBYn4Okc-r1NdQbM',
    appId: '1:744120112807:web:606a8846dcde5bff15ed82',
    messagingSenderId: '744120112807',
    projectId: 'hotelbooking-b79a6',
    authDomain: 'hotelbooking-b79a6.firebaseapp.com',
    storageBucket: 'hotelbooking-b79a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1nd5Li1onmSYGE9TqBYn4Okc-r1NdQbM',
    appId: '1:744120112807:android:606a8846dcde5bff15ed82',
    messagingSenderId: '744120112807',
    projectId: 'hotelbooking-b79a6',
    storageBucket: 'hotelbooking-b79a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1nd5Li1onmSYGE9TqBYn4Okc-r1NdQbM',
    appId: '1:744120112807:ios:606a8846dcde5bff15ed82',
    messagingSenderId: '744120112807',
    projectId: 'hotelbooking-b79a6',
    storageBucket: 'hotelbooking-b79a6.appspot.com',
    iosBundleId: 'com.example.hotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1nd5Li1onmSYGE9TqBYn4Okc-r1NdQbM',
    appId: '1:744120112807:ios:606a8846dcde5bff15ed82',
    messagingSenderId: '744120112807',
    projectId: 'hotelbooking-b79a6',
    storageBucket: 'hotelbooking-b79a6.appspot.com',
    iosBundleId: 'com.example.hotel',
  );
}
